const PixelActionTypes = {

    GRID_DATA : 'GRID_DATA',
    SELECT_PIXEL: 'SELECT_PIXEL',
    PICK_COLOR: 'PICK_COLOR',
    COLORED_PIXELS: 'COLORED_PIXELS',
    COLOR_PALETTE: 'COLOR_PALETTE',
    TOGGLE_DARK_MODE: 'TOGGLE_DARK_MODE',
    TOGGLE_DRAG_PALETTE: 'TOGGLE_DRAG_PALETTE',
    TOGGLE_GRID_BORDER: 'TOGGLE_GRID_BORDER',

};

export default PixelActionTypes;